// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: close_keys.sql

package dbsqlc

import (
	"context"
)

const insertCloseExecutionKey = `-- name: InsertCloseExecutionKey :execrows
INSERT INTO close_execution_keys (key, created_at)
VALUES ($1, NOW())
ON CONFLICT (key) DO NOTHING
`

func (q *Queries) InsertCloseExecutionKey(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, insertCloseExecutionKey, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
