// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: invites.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInviteCode = `-- name: CreateInviteCode :exec
INSERT INTO invite_codes (code, team_id, expires_at, max_uses, used_count, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
`

type CreateInviteCodeParams struct {
	Code      string             `json:"code"`
	TeamID    string             `json:"team_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   int32              `json:"max_uses"`
	UsedCount int32              `json:"used_count"`
}

func (q *Queries) CreateInviteCode(ctx context.Context, arg CreateInviteCodeParams) error {
	_, err := q.db.Exec(ctx, createInviteCode,
		arg.Code,
		arg.TeamID,
		arg.ExpiresAt,
		arg.MaxUses,
		arg.UsedCount,
	)
	return err
}

const deleteInviteCode = `-- name: DeleteInviteCode :execrows
DELETE FROM invite_codes
WHERE code = $1
`

func (q *Queries) DeleteInviteCode(ctx context.Context, code string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInviteCode, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInviteCodesByTeamID = `-- name: DeleteInviteCodesByTeamID :exec
DELETE FROM invite_codes
WHERE team_id = $1
`

func (q *Queries) DeleteInviteCodesByTeamID(ctx context.Context, teamID string) error {
	_, err := q.db.Exec(ctx, deleteInviteCodesByTeamID, teamID)
	return err
}

const getInviteCode = `-- name: GetInviteCode :one
SELECT code, team_id, expires_at, max_uses, used_count, created_at
FROM invite_codes
WHERE code = $1
`

func (q *Queries) GetInviteCode(ctx context.Context, code string) (InviteCode, error) {
	row := q.db.QueryRow(ctx, getInviteCode, code)
	var i InviteCode
	err := row.Scan(
		&i.Code,
		&i.TeamID,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.CreatedAt,
	)
	return i, err
}
