// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CloseExecutionKey struct {
	Key       string             `json:"key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type InviteCode struct {
	Code      string             `json:"code"`
	TeamID    string             `json:"team_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   int32              `json:"max_uses"`
	UsedCount int32              `json:"used_count"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MonthlyPenaltySummary struct {
	TeamID                  string   `json:"team_id"`
	Month                   string   `json:"month"`
	DailyPenaltyTotal       int32    `json:"daily_penalty_total"`
	WeeklyPenaltyTotal      int32    `json:"weekly_penalty_total"`
	IsClosed                bool     `json:"is_closed"`
	TriggeredPenaltyRuleIds []string `json:"triggered_penalty_rule_ids"`
}

type OauthAuthRequest struct {
	State        string             `json:"state"`
	Nonce        string             `json:"nonce"`
	CodeVerifier string             `json:"code_verifier"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OauthExchangeCode struct {
	Code      string             `json:"code"`
	UserID    string             `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PenaltyRule struct {
	ID          string             `json:"id"`
	TeamID      string             `json:"team_id"`
	Threshold   int32              `json:"threshold"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	Token     string             `json:"token"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Task struct {
	ID                         string             `json:"id"`
	TeamID                     string             `json:"team_id"`
	Title                      string             `json:"title"`
	Notes                      pgtype.Text        `json:"notes"`
	Type                       string             `json:"type"`
	PenaltyPoints              int32              `json:"penalty_points"`
	AssigneeUserID             string             `json:"assignee_user_id"`
	IsActive                   bool               `json:"is_active"`
	RequiredCompletionsPerWeek int32              `json:"required_completions_per_week"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type TaskCompletion struct {
	TaskID     string             `json:"task_id"`
	TargetDate pgtype.Date        `json:"target_date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Team struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TeamMember struct {
	TeamID    string             `json:"team_id"`
	UserID    string             `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          string             `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
