// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: monthly_summaries.sql

package dbsqlc

import (
	"context"
)

const closeMonthlyPenaltySummary = `-- name: CloseMonthlyPenaltySummary :exec
UPDATE monthly_penalty_summaries
SET is_closed = TRUE,
    triggered_penalty_rule_ids = $3
WHERE team_id = $1 AND month = $2
`

type CloseMonthlyPenaltySummaryParams struct {
	TeamID                  string   `json:"team_id"`
	Month                   string   `json:"month"`
	TriggeredPenaltyRuleIds []string `json:"triggered_penalty_rule_ids"`
}

func (q *Queries) CloseMonthlyPenaltySummary(ctx context.Context, arg CloseMonthlyPenaltySummaryParams) error {
	_, err := q.db.Exec(ctx, closeMonthlyPenaltySummary, arg.TeamID, arg.Month, arg.TriggeredPenaltyRuleIds)
	return err
}

const getMonthlyPenaltySummary = `-- name: GetMonthlyPenaltySummary :one
SELECT team_id, month, daily_penalty_total, weekly_penalty_total, is_closed, triggered_penalty_rule_ids
FROM monthly_penalty_summaries
WHERE team_id = $1 AND month = $2
`

type GetMonthlyPenaltySummaryParams struct {
	TeamID string `json:"team_id"`
	Month  string `json:"month"`
}

func (q *Queries) GetMonthlyPenaltySummary(ctx context.Context, arg GetMonthlyPenaltySummaryParams) (MonthlyPenaltySummary, error) {
	row := q.db.QueryRow(ctx, getMonthlyPenaltySummary, arg.TeamID, arg.Month)
	var i MonthlyPenaltySummary
	err := row.Scan(
		&i.TeamID,
		&i.Month,
		&i.DailyPenaltyTotal,
		&i.WeeklyPenaltyTotal,
		&i.IsClosed,
		&i.TriggeredPenaltyRuleIds,
	)
	return i, err
}

const incrementDailyPenalty = `-- name: IncrementDailyPenalty :exec
UPDATE monthly_penalty_summaries
SET daily_penalty_total = daily_penalty_total + $3
WHERE team_id = $1 AND month = $2
`

type IncrementDailyPenaltyParams struct {
	TeamID            string `json:"team_id"`
	Month             string `json:"month"`
	DailyPenaltyTotal int32  `json:"daily_penalty_total"`
}

func (q *Queries) IncrementDailyPenalty(ctx context.Context, arg IncrementDailyPenaltyParams) error {
	_, err := q.db.Exec(ctx, incrementDailyPenalty, arg.TeamID, arg.Month, arg.DailyPenaltyTotal)
	return err
}

const incrementWeeklyPenalty = `-- name: IncrementWeeklyPenalty :exec
UPDATE monthly_penalty_summaries
SET weekly_penalty_total = weekly_penalty_total + $3
WHERE team_id = $1 AND month = $2
`

type IncrementWeeklyPenaltyParams struct {
	TeamID             string `json:"team_id"`
	Month              string `json:"month"`
	WeeklyPenaltyTotal int32  `json:"weekly_penalty_total"`
}

func (q *Queries) IncrementWeeklyPenalty(ctx context.Context, arg IncrementWeeklyPenaltyParams) error {
	_, err := q.db.Exec(ctx, incrementWeeklyPenalty, arg.TeamID, arg.Month, arg.WeeklyPenaltyTotal)
	return err
}

const upsertMonthlyPenaltySummary = `-- name: UpsertMonthlyPenaltySummary :exec
INSERT INTO monthly_penalty_summaries (team_id, month, daily_penalty_total, weekly_penalty_total, is_closed, triggered_penalty_rule_ids)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (team_id, month) DO UPDATE SET
  daily_penalty_total = EXCLUDED.daily_penalty_total,
  weekly_penalty_total = EXCLUDED.weekly_penalty_total,
  is_closed = EXCLUDED.is_closed,
  triggered_penalty_rule_ids = EXCLUDED.triggered_penalty_rule_ids
`

type UpsertMonthlyPenaltySummaryParams struct {
	TeamID                  string   `json:"team_id"`
	Month                   string   `json:"month"`
	DailyPenaltyTotal       int32    `json:"daily_penalty_total"`
	WeeklyPenaltyTotal      int32    `json:"weekly_penalty_total"`
	IsClosed                bool     `json:"is_closed"`
	TriggeredPenaltyRuleIds []string `json:"triggered_penalty_rule_ids"`
}

func (q *Queries) UpsertMonthlyPenaltySummary(ctx context.Context, arg UpsertMonthlyPenaltySummaryParams) error {
	_, err := q.db.Exec(ctx, upsertMonthlyPenaltySummary,
		arg.TeamID,
		arg.Month,
		arg.DailyPenaltyTotal,
		arg.WeeklyPenaltyTotal,
		arg.IsClosed,
		arg.TriggeredPenaltyRuleIds,
	)
	return err
}
