// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: penalty_rules.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPenaltyRule = `-- name: CreatePenaltyRule :exec
INSERT INTO penalty_rules (id, team_id, threshold, name, description, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreatePenaltyRuleParams struct {
	ID          string             `json:"id"`
	TeamID      string             `json:"team_id"`
	Threshold   int32              `json:"threshold"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePenaltyRule(ctx context.Context, arg CreatePenaltyRuleParams) error {
	_, err := q.db.Exec(ctx, createPenaltyRule,
		arg.ID,
		arg.TeamID,
		arg.Threshold,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePenaltyRule = `-- name: DeletePenaltyRule :exec
DELETE FROM penalty_rules
WHERE id = $1
`

func (q *Queries) DeletePenaltyRule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePenaltyRule, id)
	return err
}

const getPenaltyRuleByID = `-- name: GetPenaltyRuleByID :one
SELECT id, team_id, threshold, name, description, is_active, created_at, updated_at
FROM penalty_rules
WHERE id = $1
`

func (q *Queries) GetPenaltyRuleByID(ctx context.Context, id string) (PenaltyRule, error) {
	row := q.db.QueryRow(ctx, getPenaltyRuleByID, id)
	var i PenaltyRule
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Threshold,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePenaltyRulesByTeamID = `-- name: ListActivePenaltyRulesByTeamID :many
SELECT id, team_id, threshold, name, description, is_active, created_at, updated_at
FROM penalty_rules
WHERE team_id = $1 AND is_active = TRUE
ORDER BY threshold
`

func (q *Queries) ListActivePenaltyRulesByTeamID(ctx context.Context, teamID string) ([]PenaltyRule, error) {
	rows, err := q.db.Query(ctx, listActivePenaltyRulesByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyRule
	for rows.Next() {
		var i PenaltyRule
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Threshold,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPenaltyRulesByTeamID = `-- name: ListPenaltyRulesByTeamID :many
SELECT id, team_id, threshold, name, description, is_active, created_at, updated_at
FROM penalty_rules
WHERE team_id = $1
ORDER BY threshold
`

func (q *Queries) ListPenaltyRulesByTeamID(ctx context.Context, teamID string) ([]PenaltyRule, error) {
	rows, err := q.db.Query(ctx, listPenaltyRulesByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyRule
	for rows.Next() {
		var i PenaltyRule
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Threshold,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePenaltyRule = `-- name: UpdatePenaltyRule :exec
UPDATE penalty_rules
SET threshold = $2,
    name = $3,
    description = $4,
    is_active = $5,
    updated_at = $6
WHERE id = $1
`

type UpdatePenaltyRuleParams struct {
	ID          string             `json:"id"`
	Threshold   int32              `json:"threshold"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePenaltyRule(ctx context.Context, arg UpdatePenaltyRuleParams) error {
	_, err := q.db.Exec(ctx, updatePenaltyRule,
		arg.ID,
		arg.Threshold,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.UpdatedAt,
	)
	return err
}
