// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: penalty_rules.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPenaltyRule = `-- name: CreatePenaltyRule :exec
INSERT INTO penalty_rules (id, team_id, threshold, name, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePenaltyRuleParams struct {
	ID          string             `json:"id"`
	TeamID      string             `json:"team_id"`
	Threshold   int32              `json:"threshold"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePenaltyRule(ctx context.Context, arg CreatePenaltyRuleParams) error {
	_, err := q.db.Exec(ctx, createPenaltyRule,
		arg.ID,
		arg.TeamID,
		arg.Threshold,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getPenaltyRuleByID = `-- name: GetPenaltyRuleByID :one
SELECT id, team_id, threshold, name, description, deleted_at, created_at, updated_at
FROM penalty_rules
WHERE id = $1
`

func (q *Queries) GetPenaltyRuleByID(ctx context.Context, id string) (PenaltyRule, error) {
	row := q.db.QueryRow(ctx, getPenaltyRuleByID, id)
	var i PenaltyRule
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Threshold,
		&i.Name,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUndeletedPenaltyRuleByID = `-- name: GetUndeletedPenaltyRuleByID :one
SELECT id, team_id, threshold, name, description, deleted_at, created_at, updated_at
FROM penalty_rules
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUndeletedPenaltyRuleByID(ctx context.Context, id string) (PenaltyRule, error) {
	row := q.db.QueryRow(ctx, getUndeletedPenaltyRuleByID, id)
	var i PenaltyRule
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Threshold,
		&i.Name,
		&i.Description,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPenaltyRulesByTeamID = `-- name: ListPenaltyRulesByTeamID :many
SELECT id, team_id, threshold, name, description, deleted_at, created_at, updated_at
FROM penalty_rules
WHERE team_id = $1
ORDER BY threshold
`

func (q *Queries) ListPenaltyRulesByTeamID(ctx context.Context, teamID string) ([]PenaltyRule, error) {
	rows, err := q.db.Query(ctx, listPenaltyRulesByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyRule
	for rows.Next() {
		var i PenaltyRule
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Threshold,
			&i.Name,
			&i.Description,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPenaltyRulesEffectiveAtByTeamID = `-- name: ListPenaltyRulesEffectiveAtByTeamID :many
SELECT id, team_id, threshold, name, description, deleted_at, created_at, updated_at
FROM penalty_rules
WHERE team_id = $1
  AND created_at < $2
  AND (deleted_at IS NULL OR deleted_at >= $2)
ORDER BY threshold
`

type ListPenaltyRulesEffectiveAtByTeamIDParams struct {
	TeamID string             `json:"team_id"`
	AsOf   pgtype.Timestamptz `json:"as_of"`
}

func (q *Queries) ListPenaltyRulesEffectiveAtByTeamID(ctx context.Context, arg ListPenaltyRulesEffectiveAtByTeamIDParams) ([]PenaltyRule, error) {
	rows, err := q.db.Query(ctx, listPenaltyRulesEffectiveAtByTeamID, arg.TeamID, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyRule
	for rows.Next() {
		var i PenaltyRule
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Threshold,
			&i.Name,
			&i.Description,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUndeletedPenaltyRulesByTeamID = `-- name: ListUndeletedPenaltyRulesByTeamID :many
SELECT id, team_id, threshold, name, description, deleted_at, created_at, updated_at
FROM penalty_rules
WHERE team_id = $1 AND deleted_at IS NULL
ORDER BY threshold
`

func (q *Queries) ListUndeletedPenaltyRulesByTeamID(ctx context.Context, teamID string) ([]PenaltyRule, error) {
	rows, err := q.db.Query(ctx, listUndeletedPenaltyRulesByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PenaltyRule
	for rows.Next() {
		var i PenaltyRule
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Threshold,
			&i.Name,
			&i.Description,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePenaltyRule = `-- name: SoftDeletePenaltyRule :execrows
UPDATE penalty_rules
SET deleted_at = $2,
    updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeletePenaltyRuleParams struct {
	ID        string             `json:"id"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) SoftDeletePenaltyRule(ctx context.Context, arg SoftDeletePenaltyRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePenaltyRule, arg.ID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePenaltyRule = `-- name: UpdatePenaltyRule :exec
UPDATE penalty_rules
SET threshold = $2,
    name = $3,
    description = $4,
    updated_at = $5
WHERE id = $1 AND deleted_at IS NULL
`

type UpdatePenaltyRuleParams struct {
	ID          string             `json:"id"`
	Threshold   int32              `json:"threshold"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePenaltyRule(ctx context.Context, arg UpdatePenaltyRuleParams) error {
	_, err := q.db.Exec(ctx, updatePenaltyRule,
		arg.ID,
		arg.Threshold,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
	)
	return err
}
