// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: push.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivatePushSubscriptionByEndpoint = `-- name: DeactivatePushSubscriptionByEndpoint :execrows
UPDATE push_subscriptions
SET is_active = FALSE,
    updated_at = $2
WHERE endpoint = $1
  AND is_active = TRUE
`

type DeactivatePushSubscriptionByEndpointParams struct {
	Endpoint  string             `json:"endpoint"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeactivatePushSubscriptionByEndpoint(ctx context.Context, arg DeactivatePushSubscriptionByEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivatePushSubscriptionByEndpoint, arg.Endpoint, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivatePushSubscriptionByIDAndUser = `-- name: DeactivatePushSubscriptionByIDAndUser :execrows
UPDATE push_subscriptions
SET is_active = FALSE,
    updated_at = $3
WHERE id = $1
  AND user_id = $2
`

type DeactivatePushSubscriptionByIDAndUserParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeactivatePushSubscriptionByIDAndUser(ctx context.Context, arg DeactivatePushSubscriptionByIDAndUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivatePushSubscriptionByIDAndUser, arg.ID, arg.UserID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPushDispatchState = `-- name: GetPushDispatchState :one
SELECT team_id,
       slot_kind,
       slot_date,
       fingerprint,
       sent_at,
       updated_at
FROM push_dispatch_state
WHERE team_id = $1
  AND slot_kind = $2
  AND slot_date = $3
`

type GetPushDispatchStateParams struct {
	TeamID   string      `json:"team_id"`
	SlotKind string      `json:"slot_kind"`
	SlotDate pgtype.Date `json:"slot_date"`
}

func (q *Queries) GetPushDispatchState(ctx context.Context, arg GetPushDispatchStateParams) (PushDispatchState, error) {
	row := q.db.QueryRow(ctx, getPushDispatchState, arg.TeamID, arg.SlotKind, arg.SlotDate)
	var i PushDispatchState
	err := row.Scan(
		&i.TeamID,
		&i.SlotKind,
		&i.SlotDate,
		&i.Fingerprint,
		&i.SentAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePushSubscriptionsByTeamID = `-- name: ListActivePushSubscriptionsByTeamID :many
SELECT id,
       team_id,
       user_id,
       endpoint,
       p256dh,
       auth,
       COALESCE(user_agent, '') AS user_agent,
       platform,
       is_active,
       last_seen_at,
       created_at,
       updated_at
FROM push_subscriptions
WHERE team_id = $1
  AND is_active = TRUE
ORDER BY updated_at DESC, id DESC
`

type ListActivePushSubscriptionsByTeamIDRow struct {
	ID         string             `json:"id"`
	TeamID     string             `json:"team_id"`
	UserID     string             `json:"user_id"`
	Endpoint   string             `json:"endpoint"`
	P256dh     string             `json:"p256dh"`
	Auth       string             `json:"auth"`
	UserAgent  string             `json:"user_agent"`
	Platform   string             `json:"platform"`
	IsActive   bool               `json:"is_active"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActivePushSubscriptionsByTeamID(ctx context.Context, teamID string) ([]ListActivePushSubscriptionsByTeamIDRow, error) {
	rows, err := q.db.Query(ctx, listActivePushSubscriptionsByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePushSubscriptionsByTeamIDRow
	for rows.Next() {
		var i ListActivePushSubscriptionsByTeamIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.Platform,
			&i.IsActive,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptionsByUserID = `-- name: ListPushSubscriptionsByUserID :many
SELECT id,
       team_id,
       user_id,
       endpoint,
       p256dh,
       auth,
       COALESCE(user_agent, '') AS user_agent,
       platform,
       is_active,
       last_seen_at,
       created_at,
       updated_at
FROM push_subscriptions
WHERE user_id = $1
ORDER BY is_active DESC, updated_at DESC, id DESC
`

type ListPushSubscriptionsByUserIDRow struct {
	ID         string             `json:"id"`
	TeamID     string             `json:"team_id"`
	UserID     string             `json:"user_id"`
	Endpoint   string             `json:"endpoint"`
	P256dh     string             `json:"p256dh"`
	Auth       string             `json:"auth"`
	UserAgent  string             `json:"user_agent"`
	Platform   string             `json:"platform"`
	IsActive   bool               `json:"is_active"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPushSubscriptionsByUserID(ctx context.Context, userID string) ([]ListPushSubscriptionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPushSubscriptionsByUserIDRow
	for rows.Next() {
		var i ListPushSubscriptionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.Platform,
			&i.IsActive,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamIDsForPush = `-- name: ListTeamIDsForPush :many
SELECT DISTINCT team_id
FROM push_subscriptions
WHERE is_active = TRUE
ORDER BY team_id
`

func (q *Queries) ListTeamIDsForPush(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTeamIDsForPush)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var team_id string
		if err := rows.Scan(&team_id); err != nil {
			return nil, err
		}
		items = append(items, team_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushDispatchState = `-- name: UpsertPushDispatchState :exec
INSERT INTO push_dispatch_state (
  team_id,
  slot_kind,
  slot_date,
  fingerprint,
  sent_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (team_id, slot_kind, slot_date) DO UPDATE
SET fingerprint = EXCLUDED.fingerprint,
    sent_at = EXCLUDED.sent_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertPushDispatchStateParams struct {
	TeamID      string             `json:"team_id"`
	SlotKind    string             `json:"slot_kind"`
	SlotDate    pgtype.Date        `json:"slot_date"`
	Fingerprint string             `json:"fingerprint"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPushDispatchState(ctx context.Context, arg UpsertPushDispatchStateParams) error {
	_, err := q.db.Exec(ctx, upsertPushDispatchState,
		arg.TeamID,
		arg.SlotKind,
		arg.SlotDate,
		arg.Fingerprint,
		arg.SentAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one
INSERT INTO push_subscriptions (
  id,
  team_id,
  user_id,
  endpoint,
  p256dh,
  auth,
  user_agent,
  platform,
  is_active,
  last_seen_at,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, NULLIF($7, ''), $8, TRUE, $9, $10, $11)
ON CONFLICT (endpoint) DO UPDATE
SET team_id = EXCLUDED.team_id,
    user_id = EXCLUDED.user_id,
    p256dh = EXCLUDED.p256dh,
    auth = EXCLUDED.auth,
    user_agent = EXCLUDED.user_agent,
    platform = EXCLUDED.platform,
    is_active = TRUE,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = EXCLUDED.updated_at
RETURNING id,
          team_id,
          user_id,
          endpoint,
          p256dh,
          auth,
          COALESCE(user_agent, '') AS user_agent,
          platform,
          is_active,
          last_seen_at,
          created_at,
          updated_at
`

type UpsertPushSubscriptionParams struct {
	ID         string             `json:"id"`
	TeamID     string             `json:"team_id"`
	UserID     string             `json:"user_id"`
	Endpoint   string             `json:"endpoint"`
	P256dh     string             `json:"p256dh"`
	Auth       string             `json:"auth"`
	Column7    interface{}        `json:"column_7"`
	Platform   string             `json:"platform"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type UpsertPushSubscriptionRow struct {
	ID         string             `json:"id"`
	TeamID     string             `json:"team_id"`
	UserID     string             `json:"user_id"`
	Endpoint   string             `json:"endpoint"`
	P256dh     string             `json:"p256dh"`
	Auth       string             `json:"auth"`
	UserAgent  string             `json:"user_agent"`
	Platform   string             `json:"platform"`
	IsActive   bool               `json:"is_active"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (UpsertPushSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.ID,
		arg.TeamID,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.Column7,
		arg.Platform,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UpsertPushSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.Platform,
		&i.IsActive,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
