// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"context"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	AddTriggeredRuleForMonth(ctx context.Context, arg AddTriggeredRuleForMonthParams) error
	ClearTaskAssigneeByTeamAndUser(ctx context.Context, arg ClearTaskAssigneeByTeamAndUserParams) error
	CloseMonthlyPenaltySummary(ctx context.Context, arg CloseMonthlyPenaltySummaryParams) error
	ConsumeExchangeCode(ctx context.Context, code string) error
	CreateInviteCode(ctx context.Context, arg CreateInviteCodeParams) error
	CreatePenaltyRule(ctx context.Context, arg CreatePenaltyRuleParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	CreateTaskCompletionDaily(ctx context.Context, arg CreateTaskCompletionDailyParams) error
	CreateTeam(ctx context.Context, arg CreateTeamParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DecrementTaskCompletionWeekly(ctx context.Context, arg DecrementTaskCompletionWeeklyParams) (int64, error)
	DeleteAuthRequest(ctx context.Context, state string) error
	DeleteInviteCode(ctx context.Context, code string) (int64, error)
	DeleteInviteCodesByTeamID(ctx context.Context, teamID string) error
	DeletePenaltyRule(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, token string) error
	DeleteTask(ctx context.Context, id string) error
	DeleteTaskCompletionDaily(ctx context.Context, arg DeleteTaskCompletionDailyParams) error
	DeleteTaskCompletionDailyByTaskID(ctx context.Context, taskID string) error
	DeleteTaskCompletionWeekly(ctx context.Context, arg DeleteTaskCompletionWeeklyParams) error
	DeleteTaskCompletionWeeklyByTaskID(ctx context.Context, taskID string) error
	DeleteTaskCompletionWeeklyIfZero(ctx context.Context, arg DeleteTaskCompletionWeeklyIfZeroParams) error
	DeleteTeam(ctx context.Context, id string) error
	DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) error
	DeleteTriggeredRulesByMonth(ctx context.Context, arg DeleteTriggeredRulesByMonthParams) error
	GetAuthRequest(ctx context.Context, state string) (OauthAuthRequest, error)
	GetExchangeCode(ctx context.Context, code string) (OauthExchangeCode, error)
	GetInviteCode(ctx context.Context, code string) (InviteCode, error)
	GetLatestInviteCodeByTeamID(ctx context.Context, teamID string) (InviteCode, error)
	GetMonthlyPenaltySummary(ctx context.Context, arg GetMonthlyPenaltySummaryParams) (MonthlyPenaltySummary, error)
	GetOldestOtherTeamMember(ctx context.Context, arg GetOldestOtherTeamMemberParams) (string, error)
	GetPenaltyRuleByID(ctx context.Context, id string) (PenaltyRule, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetTaskByID(ctx context.Context, id string) (GetTaskByIDRow, error)
	GetTaskCompletionWeeklyCount(ctx context.Context, arg GetTaskCompletionWeeklyCountParams) (int64, error)
	GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	HasTaskCompletionDaily(ctx context.Context, arg HasTaskCompletionDailyParams) (bool, error)
	IncrementDailyPenalty(ctx context.Context, arg IncrementDailyPenaltyParams) error
	IncrementTaskCompletionWeekly(ctx context.Context, arg IncrementTaskCompletionWeeklyParams) (int64, error)
	IncrementWeeklyPenalty(ctx context.Context, arg IncrementWeeklyPenaltyParams) error
	InsertAuthRequest(ctx context.Context, arg InsertAuthRequestParams) error
	InsertCloseExecution(ctx context.Context, arg InsertCloseExecutionParams) (int64, error)
	InsertExchangeCode(ctx context.Context, arg InsertExchangeCodeParams) error
	ListActivePenaltyRulesByTeamID(ctx context.Context, teamID string) ([]PenaltyRule, error)
	ListActiveTasksByTeamID(ctx context.Context, teamID string) ([]ListActiveTasksByTeamIDRow, error)
	ListMembershipsByUserID(ctx context.Context, userID string) ([]ListMembershipsByUserIDRow, error)
	ListPenaltyRulesByTeamID(ctx context.Context, teamID string) ([]PenaltyRule, error)
	ListTaskCompletionDailyByMonthAndTeam(ctx context.Context, arg ListTaskCompletionDailyByMonthAndTeamParams) ([]ListTaskCompletionDailyByMonthAndTeamRow, error)
	ListTaskCompletionWeeklyByMonthAndTeam(ctx context.Context, arg ListTaskCompletionWeeklyByMonthAndTeamParams) ([]ListTaskCompletionWeeklyByMonthAndTeamRow, error)
	ListTasksByTeamID(ctx context.Context, teamID string) ([]ListTasksByTeamIDRow, error)
	ListTasksForMonthlyStatusByTeam(ctx context.Context, arg ListTasksForMonthlyStatusByTeamParams) ([]ListTasksForMonthlyStatusByTeamRow, error)
	ListTeamMembersByTeamID(ctx context.Context, teamID string) ([]ListTeamMembersByTeamIDRow, error)
	ListTriggeredRuleIDsByMonth(ctx context.Context, arg ListTriggeredRuleIDsByMonthParams) ([]string, error)
	ToggleTaskCompletionWeeklyBinary(ctx context.Context, arg ToggleTaskCompletionWeeklyBinaryParams) (int64, error)
	UpdatePenaltyRule(ctx context.Context, arg UpdatePenaltyRuleParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
	UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) error
	UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) error
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) error
	UpsertMonthlyPenaltySummary(ctx context.Context, arg UpsertMonthlyPenaltySummaryParams) error
	UpsertTaskCompletionWeeklyCount(ctx context.Context, arg UpsertTaskCompletionWeeklyCountParams) error
}

var _ Querier = (*Queries)(nil)
