// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"context"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	ConsumeExchangeCode(ctx context.Context, code string) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTeam(ctx context.Context, arg CreateTeamParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAuthRequest(ctx context.Context, state string) error
	DeleteSession(ctx context.Context, token string) error
	GetAuthRequest(ctx context.Context, state string) (OauthAuthRequest, error)
	GetExchangeCode(ctx context.Context, code string) (OauthExchangeCode, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	InsertAuthRequest(ctx context.Context, arg InsertAuthRequestParams) error
	InsertExchangeCode(ctx context.Context, arg InsertExchangeCodeParams) error
	ListMembershipsByUserID(ctx context.Context, userID string) ([]ListMembershipsByUserIDRow, error)
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
}

var _ Querier = (*Queries)(nil)
