// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reminders.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReminder = `-- name: CreateReminder :exec
INSERT INTO reminders (id, team_id, title, notes, kind, schedule_type, start_date, end_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateReminderParams struct {
	ID           string             `json:"id"`
	TeamID       string             `json:"team_id"`
	Title        string             `json:"title"`
	Notes        pgtype.Text        `json:"notes"`
	Kind         string             `json:"kind"`
	ScheduleType pgtype.Text        `json:"schedule_type"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) error {
	_, err := q.db.Exec(ctx, createReminder,
		arg.ID,
		arg.TeamID,
		arg.Title,
		arg.Notes,
		arg.Kind,
		arg.ScheduleType,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteExpiredOneTimeRemindersByTeam = `-- name: DeleteExpiredOneTimeRemindersByTeam :execrows
DELETE FROM reminders
WHERE team_id = $1
  AND kind = 'one_time'
  AND start_date < $2
`

type DeleteExpiredOneTimeRemindersByTeamParams struct {
	TeamID    string      `json:"team_id"`
	StartDate pgtype.Date `json:"start_date"`
}

func (q *Queries) DeleteExpiredOneTimeRemindersByTeam(ctx context.Context, arg DeleteExpiredOneTimeRemindersByTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOneTimeRemindersByTeam, arg.TeamID, arg.StartDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReminder = `-- name: DeleteReminder :execrows
DELETE FROM reminders
WHERE id = $1
`

func (q *Queries) DeleteReminder(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReminder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReminderByID = `-- name: GetReminderByID :one
SELECT id, team_id, title, notes, kind, schedule_type, start_date, end_date, created_at, updated_at
FROM reminders
WHERE id = $1
`

func (q *Queries) GetReminderByID(ctx context.Context, id string) (Reminder, error) {
	row := q.db.QueryRow(ctx, getReminderByID, id)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Notes,
		&i.Kind,
		&i.ScheduleType,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRemindersByTeamID = `-- name: ListRemindersByTeamID :many
SELECT id, team_id, title, notes, kind, schedule_type, start_date, end_date, created_at, updated_at
FROM reminders
WHERE team_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListRemindersByTeamID(ctx context.Context, teamID string) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listRemindersByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.Notes,
			&i.Kind,
			&i.ScheduleType,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReminder = `-- name: UpdateReminder :exec
UPDATE reminders
SET title = $2,
    notes = $3,
    kind = $4,
    schedule_type = $5,
    start_date = $6,
    end_date = $7,
    updated_at = $8
WHERE id = $1
`

type UpdateReminderParams struct {
	ID           string             `json:"id"`
	Title        string             `json:"title"`
	Notes        pgtype.Text        `json:"notes"`
	Kind         string             `json:"kind"`
	ScheduleType pgtype.Text        `json:"schedule_type"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateReminder(ctx context.Context, arg UpdateReminderParams) error {
	_, err := q.db.Exec(ctx, updateReminder,
		arg.ID,
		arg.Title,
		arg.Notes,
		arg.Kind,
		arg.ScheduleType,
		arg.StartDate,
		arg.EndDate,
		arg.UpdatedAt,
	)
	return err
}
