// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: shopping_items.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const compactShoppingItemPositionsAfter = `-- name: CompactShoppingItemPositionsAfter :exec
UPDATE shopping_items
SET position = position - 1,
    updated_at = $3
WHERE team_id = $1
  AND position > $2
`

type CompactShoppingItemPositionsAfterParams struct {
	TeamID    string             `json:"team_id"`
	Position  int32              `json:"position"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CompactShoppingItemPositionsAfter(ctx context.Context, arg CompactShoppingItemPositionsAfterParams) error {
	_, err := q.db.Exec(ctx, compactShoppingItemPositionsAfter, arg.TeamID, arg.Position, arg.UpdatedAt)
	return err
}

const createShoppingItem = `-- name: CreateShoppingItem :exec
INSERT INTO shopping_items (id, team_id, name, quantity, notes, position, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateShoppingItemParams struct {
	ID        string             `json:"id"`
	TeamID    string             `json:"team_id"`
	Name      string             `json:"name"`
	Quantity  pgtype.Text        `json:"quantity"`
	Notes     pgtype.Text        `json:"notes"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateShoppingItem(ctx context.Context, arg CreateShoppingItemParams) error {
	_, err := q.db.Exec(ctx, createShoppingItem,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Quantity,
		arg.Notes,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteShoppingItem = `-- name: DeleteShoppingItem :execrows
DELETE FROM shopping_items
WHERE id = $1
`

func (q *Queries) DeleteShoppingItem(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShoppingItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getShoppingItemByID = `-- name: GetShoppingItemByID :one
SELECT id, team_id, name, quantity, notes, position, created_at, updated_at
FROM shopping_items
WHERE id = $1
`

func (q *Queries) GetShoppingItemByID(ctx context.Context, id string) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, getShoppingItemByID, id)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Quantity,
		&i.Notes,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShoppingItemMaxPositionByTeamID = `-- name: GetShoppingItemMaxPositionByTeamID :one
SELECT COALESCE(MAX(position), 0)::integer AS position
FROM shopping_items
WHERE team_id = $1
`

func (q *Queries) GetShoppingItemMaxPositionByTeamID(ctx context.Context, teamID string) (int32, error) {
	row := q.db.QueryRow(ctx, getShoppingItemMaxPositionByTeamID, teamID)
	var position int32
	err := row.Scan(&position)
	return position, err
}

const listShoppingItemsByTeamID = `-- name: ListShoppingItemsByTeamID :many
SELECT id, team_id, name, quantity, notes, position, created_at, updated_at
FROM shopping_items
WHERE team_id = $1
ORDER BY position, created_at, id
`

func (q *Queries) ListShoppingItemsByTeamID(ctx context.Context, teamID string) ([]ShoppingItem, error) {
	rows, err := q.db.Query(ctx, listShoppingItemsByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingItem
	for rows.Next() {
		var i ShoppingItem
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Quantity,
			&i.Notes,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShoppingItem = `-- name: UpdateShoppingItem :exec
UPDATE shopping_items
SET name = $2,
    quantity = $3,
    notes = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateShoppingItemParams struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Quantity  pgtype.Text        `json:"quantity"`
	Notes     pgtype.Text        `json:"notes"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateShoppingItem(ctx context.Context, arg UpdateShoppingItemParams) error {
	_, err := q.db.Exec(ctx, updateShoppingItem,
		arg.ID,
		arg.Name,
		arg.Quantity,
		arg.Notes,
		arg.UpdatedAt,
	)
	return err
}

const updateShoppingItemPosition = `-- name: UpdateShoppingItemPosition :exec
UPDATE shopping_items
SET position = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateShoppingItemPositionParams struct {
	ID        string             `json:"id"`
	Position  int32              `json:"position"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateShoppingItemPosition(ctx context.Context, arg UpdateShoppingItemPositionParams) error {
	_, err := q.db.Exec(ctx, updateShoppingItemPosition, arg.ID, arg.Position, arg.UpdatedAt)
	return err
}
