// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: shopping_items.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShoppingItem = `-- name: CreateShoppingItem :exec
INSERT INTO shopping_items (id, team_id, name, quantity, notes, sort_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateShoppingItemParams struct {
	ID        string             `json:"id"`
	TeamID    string             `json:"team_id"`
	Name      string             `json:"name"`
	Quantity  pgtype.Text        `json:"quantity"`
	Notes     pgtype.Text        `json:"notes"`
	SortKey   int32              `json:"sort_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateShoppingItem(ctx context.Context, arg CreateShoppingItemParams) error {
	_, err := q.db.Exec(ctx, createShoppingItem,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.Quantity,
		arg.Notes,
		arg.SortKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteShoppingItem = `-- name: DeleteShoppingItem :execrows
DELETE FROM shopping_items
WHERE id = $1
`

func (q *Queries) DeleteShoppingItem(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShoppingItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getShoppingItemByID = `-- name: GetShoppingItemByID :one
SELECT id, team_id, name, quantity, notes, sort_key, created_at, updated_at
FROM shopping_items
WHERE id = $1
`

func (q *Queries) GetShoppingItemByID(ctx context.Context, id string) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, getShoppingItemByID, id)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Quantity,
		&i.Notes,
		&i.SortKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShoppingItemMaxSortKeyByTeamID = `-- name: GetShoppingItemMaxSortKeyByTeamID :one
SELECT COALESCE(MAX(sort_key), 0)::integer AS sort_key
FROM shopping_items
WHERE team_id = $1
`

func (q *Queries) GetShoppingItemMaxSortKeyByTeamID(ctx context.Context, teamID string) (int32, error) {
	row := q.db.QueryRow(ctx, getShoppingItemMaxSortKeyByTeamID, teamID)
	var sort_key int32
	err := row.Scan(&sort_key)
	return sort_key, err
}

const listShoppingItemsByTeamID = `-- name: ListShoppingItemsByTeamID :many
SELECT id, team_id, name, quantity, notes, sort_key, created_at, updated_at
FROM shopping_items
WHERE team_id = $1
ORDER BY sort_key, created_at, id
`

func (q *Queries) ListShoppingItemsByTeamID(ctx context.Context, teamID string) ([]ShoppingItem, error) {
	rows, err := q.db.Query(ctx, listShoppingItemsByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingItem
	for rows.Next() {
		var i ShoppingItem
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Quantity,
			&i.Notes,
			&i.SortKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShoppingItem = `-- name: UpdateShoppingItem :exec
UPDATE shopping_items
SET name = $2,
    quantity = $3,
    notes = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateShoppingItemParams struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Quantity  pgtype.Text        `json:"quantity"`
	Notes     pgtype.Text        `json:"notes"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateShoppingItem(ctx context.Context, arg UpdateShoppingItemParams) error {
	_, err := q.db.Exec(ctx, updateShoppingItem,
		arg.ID,
		arg.Name,
		arg.Quantity,
		arg.Notes,
		arg.UpdatedAt,
	)
	return err
}

const updateShoppingItemSortKey = `-- name: UpdateShoppingItemSortKey :exec
UPDATE shopping_items
SET sort_key = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateShoppingItemSortKeyParams struct {
	ID        string             `json:"id"`
	SortKey   int32              `json:"sort_key"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateShoppingItemSortKey(ctx context.Context, arg UpdateShoppingItemSortKeyParams) error {
	_, err := q.db.Exec(ctx, updateShoppingItemSortKey, arg.ID, arg.SortKey, arg.UpdatedAt)
	return err
}
