// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teams.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (team_id, user_id) DO NOTHING
`

type AddTeamMemberParams struct {
	TeamID    string             `json:"team_id"`
	UserID    string             `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.Exec(ctx, addTeamMember,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const createTeam = `-- name: CreateTeam :exec
INSERT INTO teams (id, created_at)
VALUES ($1, $2)
`

type CreateTeamParams struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) error {
	_, err := q.db.Exec(ctx, createTeam, arg.ID, arg.CreatedAt)
	return err
}

const listMembershipsByUserID = `-- name: ListMembershipsByUserID :many
SELECT team_id, role
FROM team_members
WHERE user_id = $1
`

type ListMembershipsByUserIDRow struct {
	TeamID string `json:"team_id"`
	Role   string `json:"role"`
}

func (q *Queries) ListMembershipsByUserID(ctx context.Context, userID string) ([]ListMembershipsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsByUserIDRow
	for rows.Next() {
		var i ListMembershipsByUserIDRow
		if err := rows.Scan(&i.TeamID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
