// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, display_name, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID          string             `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.CreatedAt,
	)
	return err
}

const getUserAuthIdentityByID = `-- name: GetUserAuthIdentityByID :one
SELECT id,
       COALESCE(oidc_issuer, '') AS oidc_issuer,
       COALESCE(oidc_subject, '') AS oidc_subject
FROM users
WHERE id = $1
`

type GetUserAuthIdentityByIDRow struct {
	ID          string `json:"id"`
	OidcIssuer  string `json:"oidc_issuer"`
	OidcSubject string `json:"oidc_subject"`
}

func (q *Queries) GetUserAuthIdentityByID(ctx context.Context, id string) (GetUserAuthIdentityByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthIdentityByID, id)
	var i GetUserAuthIdentityByIDRow
	err := row.Scan(&i.ID, &i.OidcIssuer, &i.OidcSubject)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, COALESCE(nickname, '') AS nickname, color_hex, created_at
FROM users
WHERE LOWER(email) = LOWER($1)
`

type GetUserByEmailRow struct {
	ID          string             `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Nickname    string             `json:"nickname"`
	ColorHex    pgtype.Text        `json:"color_hex"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Nickname,
		&i.ColorHex,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, COALESCE(nickname, '') AS nickname, color_hex, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          string             `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	Nickname    string             `json:"nickname"`
	ColorHex    pgtype.Text        `json:"color_hex"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Nickname,
		&i.ColorHex,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserColorHex = `-- name: UpdateUserColorHex :exec
UPDATE users
SET color_hex = NULLIF($2, '')
WHERE id = $1
`

type UpdateUserColorHexParams struct {
	ID      string      `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) UpdateUserColorHex(ctx context.Context, arg UpdateUserColorHexParams) error {
	_, err := q.db.Exec(ctx, updateUserColorHex, arg.ID, arg.Column2)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users
SET display_name = $2
WHERE id = $1
`

type UpdateUserDisplayNameParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	return err
}

const updateUserNickname = `-- name: UpdateUserNickname :exec
UPDATE users
SET nickname = NULLIF($2, '')
WHERE id = $1
`

type UpdateUserNicknameParams struct {
	ID      string      `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) error {
	_, err := q.db.Exec(ctx, updateUserNickname, arg.ID, arg.Column2)
	return err
}

const updateUserOIDCByID = `-- name: UpdateUserOIDCByID :exec
UPDATE users
SET oidc_issuer = NULLIF($2, ''),
    oidc_subject = NULLIF($3, ''),
    oidc_linked_at = $4
WHERE id = $1
`

type UpdateUserOIDCByIDParams struct {
	ID           string             `json:"id"`
	Column2      interface{}        `json:"column_2"`
	Column3      interface{}        `json:"column_3"`
	OidcLinkedAt pgtype.Timestamptz `json:"oidc_linked_at"`
}

func (q *Queries) UpdateUserOIDCByID(ctx context.Context, arg UpdateUserOIDCByIDParams) error {
	_, err := q.db.Exec(ctx, updateUserOIDCByID,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.OidcLinkedAt,
	)
	return err
}
