services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    working_dir: /app/app
    restart: unless-stopped
    ports:
      - "127.0.0.1:5174:5174"
    volumes:
      - ./app:/app/app
      - app_node_modules:/app/app/node_modules

volumes:
  app_node_modules:
