FROM golang:1.24

WORKDIR /app/backend

RUN go install github.com/air-verse/air@v1.61.1 \
    && go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8

CMD ["air", "-c", ".air.toml"]
