FROM golang:1.26.4

WORKDIR /app/backend

RUN go install github.com/air-verse/air@v1.65.3 \
    && go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2

CMD ["air", "-c", ".air.toml"]
