import type { Operation } from "../../contracts/operations";
import type { TeamChangeScope } from "../../contracts/realtime";

// 読み取りと変更通知の対象を一箇所で定義する。operation追加時は型検査で対応を要求する。
export const operationChanges = {
  getMe: [],
  patchMeNickname: ["profile"],
  patchMeColor: ["profile"],
  postPushSubscription: ["push-subscriptions"],
  deletePushSubscription: ["push-subscriptions"],
  getPushSubscriptionsMe: [],
  postTeamInvite: ["invite"],
  getTeamCurrentInvite: [],
  patchTeamCurrent: ["profile"],
  getTeamCurrentMembers: [],
  postTeamJoin: ["membership"],
  postTeamLeave: ["membership"],
  listTasks: [],
  postTask: ["tasks"],
  postTasksReorder: ["tasks"],
  patchTask: ["tasks"],
  deleteTask: ["tasks"],
  postTaskCompletion: ["task-completions"],
  listReminders: [],
  postReminder: ["reminders"],
  listReminderDefinitions: [],
  patchReminder: ["reminders"],
  deleteReminder: ["reminders"],
  listPenaltyRules: [],
  postPenaltyRule: ["penalty-rules"],
  patchPenaltyRule: ["penalty-rules"],
  deletePenaltyRule: ["penalty-rules"],
  listTodoCategories: [],
  postTodoCategory: ["todo-categories"],
  patchTodoCategory: ["todo-categories"],
  deleteTodoCategory: ["todo-categories"],
  postTodoCategoriesReorder: ["todo-categories"],
  listTodoItems: [],
  postTodoItem: ["todos"],
  patchTodoItem: ["todos"],
  deleteTodoItem: ["todos"],
  postTodoItemsReorder: ["todos"],
  getTaskOverview: [],
  getPenaltySummaryMonthly: [],
  getMonthCloseCandidate: [],
  postMonthClose: ["month-close"],
} satisfies Record<Operation["operation"], TeamChangeScope[]>;
