/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.mcp.jsonc --config=wrangler.jsonc --include-runtime=false --env-interface=McpEnv mcp-worker-configuration.d.ts` (hash: 84004a0d1dd9c2d80e6c349d3832cbdb)
interface __BaseEnv_McpEnv {
	APP_ORIGIN: "http://localhost:5174";
	APP_RELEASE: "cloudflare-v1";
	MCP_ENABLED: "false";
	MCP_ORIGIN: "http://localhost:5176";
	MAINTENANCE_MODE: "false";
	KAJI_APPLICATION: Service<typeof import("./src/server-entry").McpApplication>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/transport/mcp-worker");
	}
	interface Env extends __BaseEnv_McpEnv {}
}
interface McpEnv extends __BaseEnv_McpEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "APP_RELEASE" | "MCP_ENABLED" | "MCP_ORIGIN" | "MAINTENANCE_MODE">> {}
}

// Exporting makes Cloudflare and NodeJS namespaces module-local.
export type { McpEnv };
