/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f921ba517da0888602411b08cfc4a6ea)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	APP_ORIGIN: "http://localhost:5174";
	JOBS_ENABLED: "false";
	MAINTENANCE_MODE: "false";
	APP_RELEASE: "cloudflare-v1";
	VAPID_PUBLIC_KEY: "";
	VAPID_SUBJECT: "mailto:admin@example.com";
	BETTER_AUTH_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	SIGNUP_ALLOWED_EMAILS: string;
	VAPID_PRIVATE_KEY: string;
	TEAM_REALTIME: DurableObjectNamespace<import("./src/server-entry").TeamRealtime>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server-entry");
		durableNamespaces: "TeamRealtime";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "JOBS_ENABLED" | "MAINTENANCE_MODE" | "APP_RELEASE" | "VAPID_PUBLIC_KEY" | "VAPID_SUBJECT" | "BETTER_AUTH_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "SIGNUP_ALLOWED_EMAILS" | "VAPID_PRIVATE_KEY">> {}
}
