/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppInvitesRouteImport } from './routes/_app.invites'
import { Route as AppPenaltiesRouteImport } from './routes/_app.penalties'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppShoppingListRouteImport } from './routes/_app.shopping-list'
import { Route as AppSummaryRouteImport } from './routes/_app.summary'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitesRoute = AppInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AppRoute,
} as any)
const AppPenaltiesRoute = AppPenaltiesRouteImport.update({
  id: '/penalties',
  path: '/penalties',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShoppingListRoute = AppShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => AppRoute,
} as any)
const AppSummaryRoute = AppSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/calendar': typeof AppCalendarRoute
  '/invites': typeof AppInvitesRoute
  '/penalties': typeof AppPenaltiesRoute
  '/settings': typeof AppSettingsRoute
  '/shopping-list': typeof AppShoppingListRoute
  '/summary': typeof AppSummaryRoute
  '/tasks': typeof AppTasksRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/calendar': typeof AppCalendarRoute
  '/invites': typeof AppInvitesRoute
  '/penalties': typeof AppPenaltiesRoute
  '/settings': typeof AppSettingsRoute
  '/shopping-list': typeof AppShoppingListRoute
  '/summary': typeof AppSummaryRoute
  '/tasks': typeof AppTasksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/invites': typeof AppInvitesRoute
  '/_app/penalties': typeof AppPenaltiesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shopping-list': typeof AppShoppingListRoute
  '/_app/summary': typeof AppSummaryRoute
  '/_app/tasks': typeof AppTasksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/invites'
    | '/penalties'
    | '/settings'
    | '/shopping-list'
    | '/summary'
    | '/tasks'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/calendar'
    | '/invites'
    | '/penalties'
    | '/settings'
    | '/shopping-list'
    | '/summary'
    | '/tasks'
    | '/auth/callback'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/calendar'
    | '/_app/invites'
    | '/_app/penalties'
    | '/_app/settings'
    | '/_app/shopping-list'
    | '/_app/summary'
    | '/_app/tasks'
    | '/auth/callback'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invites': {
      id: '/_app/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof AppInvitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/penalties': {
      id: '/_app/penalties'
      path: '/penalties'
      fullPath: '/penalties'
      preLoaderRoute: typeof AppPenaltiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shopping-list': {
      id: '/_app/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof AppShoppingListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/summary': {
      id: '/_app/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AppSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppInvitesRoute: typeof AppInvitesRoute
  AppPenaltiesRoute: typeof AppPenaltiesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShoppingListRoute: typeof AppShoppingListRoute
  AppSummaryRoute: typeof AppSummaryRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppInvitesRoute: AppInvitesRoute,
  AppPenaltiesRoute: AppPenaltiesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShoppingListRoute: AppShoppingListRoute,
  AppSummaryRoute: AppSummaryRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
